name: Changesets PR or Publish

on:
    push:
        branches: [main, beta]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - name: Create Changesets Pull Request or Publish to NPM
              id: changesets
              uses: changesets/action@v1
              with:
                  title: 'chore: version packages'
                  commit: 'chore: version packages'
                  version: yarn changeset:version
                  publish: yarn changeset:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
